package fr.gfi.cmg.QuizzCmg.metier.entite.hibernate;

// Generated 2 août 2013 10:03:09 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Admin generated by hbm2java
 */
public class Admin implements java.io.Serializable {

	private Integer id;
	private String libNom;
	private String libPrenom;
	private String libPassword;
	private Set<Quizz> quizzs = new HashSet<Quizz>(0);

	public Admin() {
	}

	public Admin(String libNom, String libPrenom, String libPassword, Set<Quizz> quizzs) {
		this.libNom = libNom;
		this.libPrenom = libPrenom;
		this.libPassword = libPassword;
		this.quizzs = quizzs;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getLibNom() {
		return this.libNom;
	}

	public void setLibNom(String libNom) {
		this.libNom = libNom;
	}

	public String getLibPrenom() {
		return this.libPrenom;
	}

	public void setLibPrenom(String libPrenom) {
		this.libPrenom = libPrenom;
	}

	public String getLibPassword() {
		return this.libPassword;
	}

	public void setLibPassword(String libPassword) {
		this.libPassword = libPassword;
	}

	public Set<Quizz> getQuizzs() {
		return this.quizzs;
	}

	public void setQuizzs(Set<Quizz> quizzs) {
		this.quizzs = quizzs;
	}

}
