package fr.gfi.cmg.QuizzCmg.metier.entite.hibernate;

// Generated 17 sept. 2013 15:46:48 by Hibernate Tools 3.4.0.CR1

/**
 * QuizzSujet generated by hbm2java
 */
public class QuizzSujet implements java.io.Serializable {

	private Integer id;
	private Quizz quizz;
	private TypeSujet typeSujet;
	private NiveauQuestion niveauQuestion;

	public QuizzSujet() {
	}

	public QuizzSujet(NiveauQuestion niveauQuestion) {
		this.niveauQuestion = niveauQuestion;
	}

	public QuizzSujet(Quizz quizz, TypeSujet typeSujet, NiveauQuestion niveauQuestion) {
		this.quizz = quizz;
		this.typeSujet = typeSujet;
		this.niveauQuestion = niveauQuestion;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Quizz getQuizz() {
		return this.quizz;
	}

	public void setQuizz(Quizz quizz) {
		this.quizz = quizz;
	}

	public TypeSujet getTypeSujet() {
		return this.typeSujet;
	}

	public void setTypeSujet(TypeSujet typeSujet) {
		this.typeSujet = typeSujet;
	}

	public NiveauQuestion getNiveauQuestion() {
		return this.niveauQuestion;
	}

	public void setNiveauQuestion(NiveauQuestion niveauQuestion) {
		this.niveauQuestion = niveauQuestion;
	}

}
