package fr.gfi.cmg.QuizzCmg.metier.entite.hibernate;

// Generated 2 août 2013 10:03:09 by Hibernate Tools 3.4.0.CR1

/**
 * QuizzSujet generated by hbm2java
 */
public class QuizzSujet implements java.io.Serializable {

	private Integer id;
	private Quizz quizz;
	private TypeSujet typeSujet;

	public QuizzSujet() {
	}

	public QuizzSujet(Quizz quizz, TypeSujet typeSujet) {
		this.quizz = quizz;
		this.typeSujet = typeSujet;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Quizz getQuizz() {
		return this.quizz;
	}

	public void setQuizz(Quizz quizz) {
		this.quizz = quizz;
	}

	public TypeSujet getTypeSujet() {
		return this.typeSujet;
	}

	public void setTypeSujet(TypeSujet typeSujet) {
		this.typeSujet = typeSujet;
	}

}
