package fr.gfi.cmg.QuizzCmg.metier.entite.hibernate;

// Generated 17 sept. 2013 17:50:17 by Hibernate Tools 3.4.0.CR1

/**
 * Role generated by hbm2java
 */
public class Role implements java.io.Serializable {

	private int id;
	private String libRole;

	public Role() {
	}

	public Role(int id, String libRole) {
		this.id = id;
		this.libRole = libRole;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getLibRole() {
		return this.libRole;
	}

	public void setLibRole(String libRole) {
		this.libRole = libRole;
	}

}
