package fr.gfi.cmg.QuizzCmg.metier.entite.hibernate;

// Generated 17 sept. 2013 17:50:17 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User implements java.io.Serializable {

	private Integer id;
	private String libNom;
	private String libPrenom;
	private String libPassword;
	private int idRole;
	private Set<Quizz> quizzs = new HashSet<Quizz>(0);

	public User() {
	}

	public User(int idRole) {
		this.idRole = idRole;
	}

	public User(String libNom, String libPrenom, String libPassword, int idRole, Set<Quizz> quizzs) {
		this.libNom = libNom;
		this.libPrenom = libPrenom;
		this.libPassword = libPassword;
		this.idRole = idRole;
		this.quizzs = quizzs;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getLibNom() {
		return this.libNom;
	}

	public void setLibNom(String libNom) {
		this.libNom = libNom;
	}

	public String getLibPrenom() {
		return this.libPrenom;
	}

	public void setLibPrenom(String libPrenom) {
		this.libPrenom = libPrenom;
	}

	public String getLibPassword() {
		return this.libPassword;
	}

	public void setLibPassword(String libPassword) {
		this.libPassword = libPassword;
	}

	public int getIdRole() {
		return this.idRole;
	}

	public void setIdRole(int idRole) {
		this.idRole = idRole;
	}

	public Set<Quizz> getQuizzs() {
		return this.quizzs;
	}

	public void setQuizzs(Set<Quizz> quizzs) {
		this.quizzs = quizzs;
	}

}
