package fr.gfi.quiz.entite.hibernate;

// Generated 2 avr. 2014 11:27:10 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 *
 * Difficulte generated by hbm2java
 */
public class Difficulte implements java.io.Serializable {

	private int id;
	private String libDifficulte;
	private Set<TypeSujet> typeSujets = new HashSet<TypeSujet>(0);

	public Difficulte() {
	}

	public Difficulte(int id) {
		this.id = id;
	}

	public Difficulte(int id, String libDifficulte, Set<TypeSujet> typeSujets) {
		this.id = id;
		this.libDifficulte = libDifficulte;
		this.typeSujets = typeSujets;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int pid) {
		this.id = pid;
	}

	public String getLibDifficulte() {
		return this.libDifficulte;
	}

	public void setLibDifficulte(String plibDifficulte) {
		this.libDifficulte = plibDifficulte;
	}

	public Set<TypeSujet> getTypeSujets() {
		return this.typeSujets;
	}

	public void setTypeSujets(Set<TypeSujet> ptypeSujets) {
		this.typeSujets = ptypeSujets;
	}

	// The following is extra code specified in the hbm.xml files   toString
	public String toString() {
		StringBuffer buffer = new StringBuffer();
		buffer.append(getClass().getName()).append("@").append(Integer.toHexString(hashCode())).append(" [");
		buffer.append("id").append("='").append(getId()).append("' ");
		buffer.append("libDifficulte").append("='").append(getLibDifficulte()).append("' ");
		buffer.append("typeSujets").append("='").append(getTypeSujets()).append("' ");
		buffer.append("]");
		return buffer.toString();
	}

}
