package fr.gfi.quiz.entite.hibernate;
// Generated 14 avr. 2014 16:36:23 by Hibernate Tools 4.0.0


import java.util.HashSet;
import java.util.Set;

/**
 * Difficulte generated by hbm2java
 */
public class Difficulte  implements java.io.Serializable {


     private int id;
     private String libDifficulte;
     private Set<Sujet> sujets = new HashSet<Sujet>(0);

    public Difficulte() {
    }

	
    public Difficulte(int id) {
        this.id = id;
    }
    public Difficulte(int id, String libDifficulte, Set<Sujet> sujets) {
       this.id = id;
       this.libDifficulte = libDifficulte;
       this.sujets = sujets;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getLibDifficulte() {
        return this.libDifficulte;
    }
    
    public void setLibDifficulte(String libDifficulte) {
        this.libDifficulte = libDifficulte;
    }
    public Set<Sujet> getSujets() {
        return this.sujets;
    }
    
    public void setSujets(Set<Sujet> sujets) {
        this.sujets = sujets;
    }




}


