package fr.gfi.quiz.entite.hibernate;

// Generated 26 mars 2014 17:52:51 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Question generated by hbm2java
 */
public class Question implements java.io.Serializable {

	private Integer id;
	private TypeSujet typeSujet;
	private String libQuestion;
	private Date datCreation;
	private Integer intDureeReflexion;
	private Boolean bolUniqueReponse;
	private String urlImage;
	private Boolean isValid;
	private Set<QuizzQuestion> quizzQuestions = new HashSet<QuizzQuestion>(0);
	private Set<ReponseCandidat> reponseCandidats = new HashSet<ReponseCandidat>(
			0);
	private Set<Reponse> reponses = new HashSet<Reponse>(0);

	public Question() {
	}

	public Question(TypeSujet typeSujet) {
		this.typeSujet = typeSujet;
	}

	public Question(TypeSujet typeSujet, String libQuestion, Date datCreation,
			Integer intDureeReflexion, Boolean bolUniqueReponse,
			String urlImage, Boolean isValid,
			Set<QuizzQuestion> quizzQuestions,
			Set<ReponseCandidat> reponseCandidats, Set<Reponse> reponses) {
		this.typeSujet = typeSujet;
		this.libQuestion = libQuestion;
		this.datCreation = datCreation;
		this.intDureeReflexion = intDureeReflexion;
		this.bolUniqueReponse = bolUniqueReponse;
		this.urlImage = urlImage;
		this.isValid = isValid;
		this.quizzQuestions = quizzQuestions;
		this.reponseCandidats = reponseCandidats;
		this.reponses = reponses;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public TypeSujet getTypeSujet() {
		return this.typeSujet;
	}

	public void setTypeSujet(TypeSujet typeSujet) {
		this.typeSujet = typeSujet;
	}

	public String getLibQuestion() {
		return this.libQuestion;
	}

	public void setLibQuestion(String libQuestion) {
		this.libQuestion = libQuestion;
	}

	public Date getDatCreation() {
		return this.datCreation;
	}

	public void setDatCreation(Date datCreation) {
		this.datCreation = datCreation;
	}

	public Integer getIntDureeReflexion() {
		return this.intDureeReflexion;
	}

	public void setIntDureeReflexion(Integer intDureeReflexion) {
		this.intDureeReflexion = intDureeReflexion;
	}

	public Boolean getBolUniqueReponse() {
		return this.bolUniqueReponse;
	}

	public void setBolUniqueReponse(Boolean bolUniqueReponse) {
		this.bolUniqueReponse = bolUniqueReponse;
	}

	public String getUrlImage() {
		return this.urlImage;
	}

	public void setUrlImage(String urlImage) {
		this.urlImage = urlImage;
	}

	public Boolean getIsValid() {
		return this.isValid;
	}

	public void setIsValid(Boolean isValid) {
		this.isValid = isValid;
	}

	public Set<QuizzQuestion> getQuizzQuestions() {
		return this.quizzQuestions;
	}

	public void setQuizzQuestions(Set<QuizzQuestion> quizzQuestions) {
		this.quizzQuestions = quizzQuestions;
	}

	public Set<ReponseCandidat> getReponseCandidats() {
		return this.reponseCandidats;
	}

	public void setReponseCandidats(Set<ReponseCandidat> reponseCandidats) {
		this.reponseCandidats = reponseCandidats;
	}

	public Set<Reponse> getReponses() {
		return this.reponses;
	}

	public void setReponses(Set<Reponse> reponses) {
		this.reponses = reponses;
	}

}
