package fr.gfi.quiz.entite.hibernate;

// Generated 2 avr. 2014 11:27:10 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 *
 * Quizz generated by hbm2java
 */
public class Quizz implements java.io.Serializable {

	private Integer id;
	private User user;
	private Integer intDuree;
	private String prenomCandidat;
	private String nomCandidat;
	private String libCommentaire;
	/**
	 * date du passage du quizz par le candidat
	 */
	private Date datQuizz;
	private Set<QuizzQuestion> quizzQuestions = new HashSet<QuizzQuestion>(0);
	private Set<QuizzSujet> quizzSujets = new HashSet<QuizzSujet>(0);
	private Set<ReponseCandidat> reponseCandidats = new HashSet<ReponseCandidat>(0);

	public Quizz() {
	}

	public Quizz(User user) {
		this.user = user;
	}

	public Quizz(User user, Integer intDuree, String prenomCandidat, String nomCandidat, String libCommentaire,
			Date datQuizz, Set<QuizzQuestion> quizzQuestions, Set<QuizzSujet> quizzSujets,
			Set<ReponseCandidat> reponseCandidats) {
		this.user = user;
		this.intDuree = intDuree;
		this.prenomCandidat = prenomCandidat;
		this.nomCandidat = nomCandidat;
		this.libCommentaire = libCommentaire;
		this.datQuizz = datQuizz;
		this.quizzQuestions = quizzQuestions;
		this.quizzSujets = quizzSujets;
		this.reponseCandidats = reponseCandidats;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer pid) {
		this.id = pid;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User puser) {
		this.user = puser;
	}

	public Integer getIntDuree() {
		return this.intDuree;
	}

	public void setIntDuree(Integer pintDuree) {
		this.intDuree = pintDuree;
	}

	public String getPrenomCandidat() {
		return this.prenomCandidat;
	}

	public void setPrenomCandidat(String pprenomCandidat) {
		this.prenomCandidat = pprenomCandidat;
	}

	public String getNomCandidat() {
		return this.nomCandidat;
	}

	public void setNomCandidat(String pnomCandidat) {
		this.nomCandidat = pnomCandidat;
	}

	public String getLibCommentaire() {
		return this.libCommentaire;
	}

	public void setLibCommentaire(String plibCommentaire) {
		this.libCommentaire = plibCommentaire;
	}

	/**
	 * date du passage du quizz par le candidat
	 */
	public Date getDatQuizz() {
		return this.datQuizz;
	}

	/**
	 * date du passage du quizz par le candidat
	 */
	public void setDatQuizz(Date pdatQuizz) {
		this.datQuizz = pdatQuizz;
	}

	public Set<QuizzQuestion> getQuizzQuestions() {
		return this.quizzQuestions;
	}

	public void setQuizzQuestions(Set<QuizzQuestion> pquizzQuestions) {
		this.quizzQuestions = pquizzQuestions;
	}

	public Set<QuizzSujet> getQuizzSujets() {
		return this.quizzSujets;
	}

	public void setQuizzSujets(Set<QuizzSujet> pquizzSujets) {
		this.quizzSujets = pquizzSujets;
	}

	public Set<ReponseCandidat> getReponseCandidats() {
		return this.reponseCandidats;
	}

	public void setReponseCandidats(Set<ReponseCandidat> preponseCandidats) {
		this.reponseCandidats = preponseCandidats;
	}

}
