package fr.gfi.quiz.entite.hibernate;

// Generated Mar 19, 2014 12:00:06 AM by Hibernate Tools 4.0.0

/**
 * QuizzSujet generated by hbm2java
 */
public class QuizzSujet implements java.io.Serializable {

	private Integer id;
	private Quizz quizz;
	private TypeSujet typeSujet;
	private NiveauQuestion niveauQuestion;

	public QuizzSujet() {
	}

	public QuizzSujet(NiveauQuestion niveauQuestion) {
		this.niveauQuestion = niveauQuestion;
	}

	public QuizzSujet(Quizz quizz, TypeSujet typeSujet,
			NiveauQuestion niveauQuestion) {
		this.quizz = quizz;
		this.typeSujet = typeSujet;
		this.niveauQuestion = niveauQuestion;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Quizz getQuizz() {
		return this.quizz;
	}

	public void setQuizz(Quizz quizz) {
		this.quizz = quizz;
	}

	public TypeSujet getTypeSujet() {
		return this.typeSujet;
	}

	public void setTypeSujet(TypeSujet typeSujet) {
		this.typeSujet = typeSujet;
	}

	public NiveauQuestion getNiveauQuestion() {
		return this.niveauQuestion;
	}

	public void setNiveauQuestion(NiveauQuestion niveauQuestion) {
		this.niveauQuestion = niveauQuestion;
	}

}
