package fr.gfi.quiz.entite.hibernate;

// Generated 14 avr. 2014 16:36:23 by Hibernate Tools 4.0.0

/**
 * QuizzSujet generated by hbm2java
 */
public class QuizzSujet implements java.io.Serializable {

	private Integer id;
	private Sujet sujet;
	private Quizz quizz;
	private Integer nbQuestion;
	private Integer nbQuestionOk;
	private Integer nbQuestionDemiOk;

	public QuizzSujet() {
	}

	public QuizzSujet(Sujet sujet) {
		this.sujet = sujet;
	}

	public QuizzSujet(Sujet sujet, Quizz quizz, Integer nbQuestion,
			Integer nbQuestionOk, Integer nbQuestionDemiOk) {
		this.sujet = sujet;
		this.quizz = quizz;
		this.nbQuestion = nbQuestion;
		this.nbQuestionOk = nbQuestionOk;
		this.nbQuestionDemiOk = nbQuestionDemiOk;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Sujet getSujet() {
		return this.sujet;
	}

	public void setSujet(Sujet sujet) {
		this.sujet = sujet;
	}

	public Quizz getQuizz() {
		return this.quizz;
	}

	public void setQuizz(Quizz quizz) {
		this.quizz = quizz;
	}

	public Integer getNbQuestion() {
		return this.nbQuestion;
	}

	public void setNbQuestion(Integer nbQuestion) {
		this.nbQuestion = nbQuestion;
	}

	public Integer getNbQuestionOk() {
		return this.nbQuestionOk;
	}

	public void setNbQuestionOk(Integer nbQuestionOk) {
		this.nbQuestionOk = nbQuestionOk;
	}

	public Integer getNbQuestionDemiOk() {
		return this.nbQuestionDemiOk;
	}

	public void setNbQuestionDemiOk(Integer nbQuestionDemiOk) {
		this.nbQuestionDemiOk = nbQuestionDemiOk;
	}

}
