package fr.gfi.quiz.entite.hibernate;
// Generated 14 avr. 2014 16:36:23 by Hibernate Tools 4.0.0



/**
 * ReponseCandidat generated by hbm2java
 */
public class ReponseCandidat  implements java.io.Serializable {


     private Integer id;
     private Question question;
     private Reponse reponse;
     private Quizz quizz;

    public ReponseCandidat() {
    }

	
    public ReponseCandidat(Question question) {
        this.question = question;
    }
    public ReponseCandidat(Question question, Reponse reponse, Quizz quizz) {
       this.question = question;
       this.reponse = reponse;
       this.quizz = quizz;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Question getQuestion() {
        return this.question;
    }
    
    public void setQuestion(Question question) {
        this.question = question;
    }
    public Reponse getReponse() {
        return this.reponse;
    }
    
    public void setReponse(Reponse reponse) {
        this.reponse = reponse;
    }
    public Quizz getQuizz() {
        return this.quizz;
    }
    
    public void setQuizz(Quizz quizz) {
        this.quizz = quizz;
    }




}


