package fr.gfi.quiz.entite.hibernate;

// Generated 2 avr. 2014 11:27:10 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 *
 * Reponse generated by hbm2java
 */
public class Reponse implements java.io.Serializable {

	private Integer id;
	private Question question;
	/**
	 * r
	 */
	private String libReponse;
	/**
	 * indique s'il s'agit d'une bonne  r
	 */
	private Boolean bolTypeReponse;
	private Set<ReponseCandidat> reponseCandidats = new HashSet<ReponseCandidat>(0);

	public Reponse() {
	}

	public Reponse(Question question) {
		this.question = question;
	}

	public Reponse(Question question, String libReponse, Boolean bolTypeReponse, Set<ReponseCandidat> reponseCandidats) {
		this.question = question;
		this.libReponse = libReponse;
		this.bolTypeReponse = bolTypeReponse;
		this.reponseCandidats = reponseCandidats;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer pid) {
		this.id = pid;
	}

	public Question getQuestion() {
		return this.question;
	}

	public void setQuestion(Question pquestion) {
		this.question = pquestion;
	}

	/**
	 * r
	 */
	public String getLibReponse() {
		return this.libReponse;
	}

	/**
	 * r
	 */
	public void setLibReponse(String plibReponse) {
		this.libReponse = plibReponse;
	}

	/**
	 * indique s'il s'agit d'une bonne  r
	 */
	public Boolean getBolTypeReponse() {
		return this.bolTypeReponse;
	}

	/**
	 * indique s'il s'agit d'une bonne  r
	 */
	public void setBolTypeReponse(Boolean pbolTypeReponse) {
		this.bolTypeReponse = pbolTypeReponse;
	}

	public Set<ReponseCandidat> getReponseCandidats() {
		return this.reponseCandidats;
	}

	public void setReponseCandidats(Set<ReponseCandidat> preponseCandidats) {
		this.reponseCandidats = preponseCandidats;
	}

	// The following is extra code specified in the hbm.xml files   toString
	public String toString() {
		StringBuffer buffer = new StringBuffer();
		buffer.append(getClass().getName()).append("@").append(Integer.toHexString(hashCode())).append(" [");
		buffer.append("id").append("='").append(getId()).append("' ");
		buffer.append("question").append("='").append(getQuestion()).append("' ");
		buffer.append("libReponse").append("='").append(getLibReponse()).append("' ");
		buffer.append("bolTypeReponse").append("='").append(getBolTypeReponse()).append("' ");
		buffer.append("reponseCandidats").append("='").append(getReponseCandidats()).append("' ");
		buffer.append("]");
		return buffer.toString();
	}

}
