package fr.gfi.quiz.entite.hibernate;

// Generated Mar 19, 2014 12:00:06 AM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * Role generated by hbm2java
 */
public class Role implements java.io.Serializable {

	private int id;
	private String libRole;
	private Set<UserRoles> userRoleses = new HashSet<UserRoles>(0);

	public Role() {
	}

	public Role(int id, String libRole) {
		this.id = id;
		this.libRole = libRole;
	}

	public Role(int id, String libRole, Set<UserRoles> userRoleses) {
		this.id = id;
		this.libRole = libRole;
		this.userRoleses = userRoleses;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getLibRole() {
		return this.libRole;
	}

	public void setLibRole(String libRole) {
		this.libRole = libRole;
	}

	public Set<UserRoles> getUserRoleses() {
		return this.userRoleses;
	}

	public void setUserRoleses(Set<UserRoles> userRoleses) {
		this.userRoleses = userRoleses;
	}

}
