package fr.gfi.quiz.entite.hibernate;

// Generated 14 avr. 2014 16:36:23 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * Theme generated by hbm2java
 */
public class Theme implements java.io.Serializable {

	private Integer id;
	private String libelle;
	private Set<Sujet> sujets = new HashSet<Sujet>(0);

	public Theme() {
	}

	public Theme(String libelle) {
		this.libelle = libelle;
	}

	public Theme(String libelle, Set<Sujet> sujets) {
		this.libelle = libelle;
		this.sujets = sujets;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getLibelle() {
		return this.libelle;
	}

	public void setLibelle(String libelle) {
		this.libelle = libelle;
	}

	public Set<Sujet> getSujets() {
		return this.sujets;
	}

	public void setSujets(Set<Sujet> sujets) {
		this.sujets = sujets;
	}

}
