package fr.gfi.quiz.entite.hibernate;

// Generated 26 mars 2014 17:52:51 by Hibernate Tools 3.4.0.CR1

/**
 * TypeSujetId generated by hbm2java
 */
public class TypeSujetId implements java.io.Serializable {

	private int id;
	private int refDifficulte;

	public TypeSujetId() {
	}

	public TypeSujetId(int id, int refDifficulte) {
		this.id = id;
		this.refDifficulte = refDifficulte;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public int getRefDifficulte() {
		return this.refDifficulte;
	}

	public void setRefDifficulte(int refDifficulte) {
		this.refDifficulte = refDifficulte;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TypeSujetId))
			return false;
		TypeSujetId castOther = (TypeSujetId) other;

		return (this.getId() == castOther.getId())
				&& (this.getRefDifficulte() == castOther.getRefDifficulte());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getId();
		result = 37 * result + this.getRefDifficulte();
		return result;
	}

}
