package fr.gfi.quiz.entite.hibernate;

// Generated 2 avr. 2014 11:27:10 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 *
 * TypeSujet generated by hbm2java
 */
public class TypeSujet implements java.io.Serializable {

	private TypeSujetId id;
	private Difficulte difficulte;
	/**
	 * cl
	 */
	private Langage langage;
	/**
	 * libell
	 */
	private String libelle;
	private Set<Question> questions = new HashSet<Question>(0);
	private Set<QuizzSujet> quizzSujets = new HashSet<QuizzSujet>(0);

	public TypeSujet() {
	}

	public TypeSujet(TypeSujetId id, Difficulte difficulte, Langage langage, String libelle) {
		this.id = id;
		this.difficulte = difficulte;
		this.langage = langage;
		this.libelle = libelle;
	}

	public TypeSujet(TypeSujetId id, Difficulte difficulte, Langage langage, String libelle, Set<Question> questions,
			Set<QuizzSujet> quizzSujets) {
		this.id = id;
		this.difficulte = difficulte;
		this.langage = langage;
		this.libelle = libelle;
		this.questions = questions;
		this.quizzSujets = quizzSujets;
	}

	public TypeSujetId getId() {
		return this.id;
	}

	public void setId(TypeSujetId pid) {
		this.id = pid;
	}

	public Difficulte getDifficulte() {
		return this.difficulte;
	}

	public void setDifficulte(Difficulte pdifficulte) {
		this.difficulte = pdifficulte;
	}

	/**
	 * cl
	 */
	public Langage getLangage() {
		return this.langage;
	}

	/**
	 * cl
	 */
	public void setLangage(Langage plangage) {
		this.langage = plangage;
	}

	/**
	 * libell
	 */
	public String getLibelle() {
		return this.libelle;
	}

	/**
	 * libell
	 */
	public void setLibelle(String plibelle) {
		this.libelle = plibelle;
	}

	public Set<Question> getQuestions() {
		return this.questions;
	}

	public void setQuestions(Set<Question> pquestions) {
		this.questions = pquestions;
	}

	public Set<QuizzSujet> getQuizzSujets() {
		return this.quizzSujets;
	}

	public void setQuizzSujets(Set<QuizzSujet> pquizzSujets) {
		this.quizzSujets = pquizzSujets;
	}

	// The following is extra code specified in the hbm.xml files   toString
	public String toString() {
		StringBuffer buffer = new StringBuffer();
		buffer.append(getClass().getName()).append("@").append(Integer.toHexString(hashCode())).append(" [");
		buffer.append("id").append("='").append(getId()).append("' ");
		buffer.append("difficulte").append("='").append(getDifficulte()).append("' ");
		buffer.append("langage").append("='").append(getLangage()).append("' ");
		buffer.append("libelle").append("='").append(getLibelle()).append("' ");
		buffer.append("questions").append("='").append(getQuestions()).append("' ");
		buffer.append("quizzSujets").append("='").append(getQuizzSujets()).append("' ");
		buffer.append("]");
		return buffer.toString();
	}

}
