package fr.gfi.quiz.entite.hibernate;

// Generated 2 avr. 2014 11:27:10 by Hibernate Tools 3.4.0.CR1

/**
 *
 * UserRoles generated by hbm2java
 */
public class UserRoles implements java.io.Serializable {

	private Integer userRoleId;
	private User user;
	private Role role;

	public UserRoles() {
	}

	public UserRoles(User user, Role role) {
		this.user = user;
		this.role = role;
	}

	public Integer getUserRoleId() {
		return this.userRoleId;
	}

	public void setUserRoleId(Integer puserRoleId) {
		this.userRoleId = puserRoleId;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User puser) {
		this.user = puser;
	}

	public Role getRole() {
		return this.role;
	}

	public void setRole(Role prole) {
		this.role = prole;
	}

	// The following is extra code specified in the hbm.xml files   toString
	public String toString() {
		StringBuffer buffer = new StringBuffer();
		buffer.append(getClass().getName()).append("@").append(Integer.toHexString(hashCode())).append(" [");
		buffer.append("userRoleId").append("='").append(getUserRoleId()).append("' ");
		buffer.append("user").append("='").append(getUser()).append("' ");
		buffer.append("role").append("='").append(getRole()).append("' ");
		buffer.append("]");
		return buffer.toString();
	}

}
