package fr.gfi.quiz.entite.hibernate;

// Generated 18 mars 2014 17:00:25 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User implements java.io.Serializable {

	private Integer id;
	private String libNom;
	private String libPrenom;
	private String libPassword;
	private Set<Quizz> quizzs = new HashSet<Quizz>(0);
	private Set<UserRoles> userRoleses = new HashSet<UserRoles>(0);

	public User() {
	}

	public User(String libNom, String libPrenom, String libPassword,
			Set<Quizz> quizzs, Set<UserRoles> userRoleses) {
		this.libNom = libNom;
		this.libPrenom = libPrenom;
		this.libPassword = libPassword;
		this.quizzs = quizzs;
		this.userRoleses = userRoleses;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getLibNom() {
		return this.libNom;
	}

	public void setLibNom(String libNom) {
		this.libNom = libNom;
	}

	public String getLibPrenom() {
		return this.libPrenom;
	}

	public void setLibPrenom(String libPrenom) {
		this.libPrenom = libPrenom;
	}

	public String getLibPassword() {
		return this.libPassword;
	}

	public void setLibPassword(String libPassword) {
		this.libPassword = libPassword;
	}

	public Set<Quizz> getQuizzs() {
		return this.quizzs;
	}

	public void setQuizzs(Set<Quizz> quizzs) {
		this.quizzs = quizzs;
	}

	public Set<UserRoles> getUserRoleses() {
		return this.userRoleses;
	}

	public void setUserRoleses(Set<UserRoles> userRoleses) {
		this.userRoleses = userRoleses;
	}

}
