package fr.gfi.quiz.entite.hibernate;

// Generated 26 mars 2014 17:52:51 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Difficulte generated by hbm2java
 */
public class Difficulte implements java.io.Serializable {

	private int id;
	private String libDifficulte;
	private Set<TypeSujet> typeSujets = new HashSet<TypeSujet>(0);

	public Difficulte() {
	}

	public Difficulte(int id) {
		this.id = id;
	}

	public Difficulte(int id, String libDifficulte, Set<TypeSujet> typeSujets) {
		this.id = id;
		this.libDifficulte = libDifficulte;
		this.typeSujets = typeSujets;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getLibDifficulte() {
		return this.libDifficulte;
	}

	public void setLibDifficulte(String libDifficulte) {
		this.libDifficulte = libDifficulte;
	}

	public Set<TypeSujet> getTypeSujets() {
		return this.typeSujets;
	}

	public void setTypeSujets(Set<TypeSujet> typeSujets) {
		this.typeSujets = typeSujets;
	}

}
