package fr.gfi.quiz.entite.hibernate;

// Generated 2 avr. 2014 11:27:10 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 *
 * Langage generated by hbm2java
 */
public class Langage implements java.io.Serializable {

	/**
	 * id unique de la table langage
	 */
	private Integer id;
	/**
	 * libelle du langage (exemple jee,java,...)
	 */
	private String libelle;
	private Set<TypeSujet> typeSujets = new HashSet<TypeSujet>(0);

	public Langage() {
	}

	public Langage(String libelle) {
		this.libelle = libelle;
	}

	public Langage(String libelle, Set<TypeSujet> typeSujets) {
		this.libelle = libelle;
		this.typeSujets = typeSujets;
	}

	/**
	 * id unique de la table langage
	 */
	public Integer getId() {
		return this.id;
	}

	/**
	 * id unique de la table langage
	 */
	public void setId(Integer pid) {
		this.id = pid;
	}

	/**
	 * libelle du langage (exemple jee,java,...)
	 */
	public String getLibelle() {
		return this.libelle;
	}

	/**
	 * libelle du langage (exemple jee,java,...)
	 */
	public void setLibelle(String plibelle) {
		this.libelle = plibelle;
	}

	public Set<TypeSujet> getTypeSujets() {
		return this.typeSujets;
	}

	public void setTypeSujets(Set<TypeSujet> ptypeSujets) {
		this.typeSujets = ptypeSujets;
	}

	// The following is extra code specified in the hbm.xml files   toString
	public String toString() {
		StringBuffer buffer = new StringBuffer();
		buffer.append(getClass().getName()).append("@").append(Integer.toHexString(hashCode())).append(" [");
		buffer.append("id").append("='").append(getId()).append("' ");
		buffer.append("libelle").append("='").append(getLibelle()).append("' ");
		buffer.append("typeSujets").append("='").append(getTypeSujets()).append("' ");
		buffer.append("]");
		return buffer.toString();
	}

}
