package fr.gfi.quiz.entite.hibernate;

// Generated Mar 19, 2014 12:00:06 AM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * Langage generated by hbm2java
 */
public class Langage implements java.io.Serializable {

	private Integer id;
	private String libelle;
	private Set<TypeSujet> typeSujets = new HashSet<TypeSujet>(0);

	public Langage() {
	}

	public Langage(String libelle) {
		this.libelle = libelle;
	}

	public Langage(String libelle, Set<TypeSujet> typeSujets) {
		this.libelle = libelle;
		this.typeSujets = typeSujets;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getLibelle() {
		return this.libelle;
	}

	public void setLibelle(String libelle) {
		this.libelle = libelle;
	}

	public Set<TypeSujet> getTypeSujets() {
		return this.typeSujets;
	}

	public void setTypeSujets(Set<TypeSujet> typeSujets) {
		this.typeSujets = typeSujets;
	}

}
