package fr.gfi.quiz.entite.hibernate;

// Generated 2 avr. 2014 11:27:10 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 *
 * Question generated by hbm2java
 */
public class Question implements java.io.Serializable {

	private Integer id;
	/**
	 * cl
	 */
	/**
	 * difficult
	 */
	private TypeSujet typeSujet;
	/**
	 * libell
	 */
	private String libQuestion;
	/**
	 * date de cr
	 */
	private Date datCreation;
	/**
	 * dur
	 */
	private Integer intDureeReflexion;
	/**
	 * indique si une question a une ou plusieurs r
	 */
	private Boolean bolUniqueReponse;
	/**
	 * url d'une 
	 */
	private String urlImage;
	/**
	 * indique si une question est toujours valide c'est 
	 */
	private Boolean isValid;
	private Set<QuizzQuestion> quizzQuestions = new HashSet<QuizzQuestion>(0);
	private Set<ReponseCandidat> reponseCandidats = new HashSet<ReponseCandidat>(0);
	private Set<Reponse> reponses = new HashSet<Reponse>(0);

	public Question() {
	}

	public Question(TypeSujet typeSujet) {
		this.typeSujet = typeSujet;
	}

	public Question(TypeSujet typeSujet, String libQuestion, Date datCreation, Integer intDureeReflexion,
			Boolean bolUniqueReponse, String urlImage, Boolean isValid, Set<QuizzQuestion> quizzQuestions,
			Set<ReponseCandidat> reponseCandidats, Set<Reponse> reponses) {
		this.typeSujet = typeSujet;
		this.libQuestion = libQuestion;
		this.datCreation = datCreation;
		this.intDureeReflexion = intDureeReflexion;
		this.bolUniqueReponse = bolUniqueReponse;
		this.urlImage = urlImage;
		this.isValid = isValid;
		this.quizzQuestions = quizzQuestions;
		this.reponseCandidats = reponseCandidats;
		this.reponses = reponses;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer pid) {
		this.id = pid;
	}

	/**
	 * cl
	 */
	/**
	 * difficult
	 */
	public TypeSujet getTypeSujet() {
		return this.typeSujet;
	}

	/**
	 * cl
	 */
	/**
	 * difficult
	 */
	public void setTypeSujet(TypeSujet ptypeSujet) {
		this.typeSujet = ptypeSujet;
	}

	/**
	 * libell
	 */
	public String getLibQuestion() {
		return this.libQuestion;
	}

	/**
	 * libell
	 */
	public void setLibQuestion(String plibQuestion) {
		this.libQuestion = plibQuestion;
	}

	/**
	 * date de cr
	 */
	public Date getDatCreation() {
		return this.datCreation;
	}

	/**
	 * date de cr
	 */
	public void setDatCreation(Date pdatCreation) {
		this.datCreation = pdatCreation;
	}

	/**
	 * dur
	 */
	public Integer getIntDureeReflexion() {
		return this.intDureeReflexion;
	}

	/**
	 * dur
	 */
	public void setIntDureeReflexion(Integer pintDureeReflexion) {
		this.intDureeReflexion = pintDureeReflexion;
	}

	/**
	 * indique si une question a une ou plusieurs r
	 */
	public Boolean getBolUniqueReponse() {
		return this.bolUniqueReponse;
	}

	/**
	 * indique si une question a une ou plusieurs r
	 */
	public void setBolUniqueReponse(Boolean pbolUniqueReponse) {
		this.bolUniqueReponse = pbolUniqueReponse;
	}

	/**
	 * url d'une 
	 */
	public String getUrlImage() {
		return this.urlImage;
	}

	/**
	 * url d'une 
	 */
	public void setUrlImage(String purlImage) {
		this.urlImage = purlImage;
	}

	/**
	 * indique si une question est toujours valide c'est 
	 */
	public Boolean getIsValid() {
		return this.isValid;
	}

	/**
	 * indique si une question est toujours valide c'est 
	 */
	public void setIsValid(Boolean pisValid) {
		this.isValid = pisValid;
	}

	public Set<QuizzQuestion> getQuizzQuestions() {
		return this.quizzQuestions;
	}

	public void setQuizzQuestions(Set<QuizzQuestion> pquizzQuestions) {
		this.quizzQuestions = pquizzQuestions;
	}

	public Set<ReponseCandidat> getReponseCandidats() {
		return this.reponseCandidats;
	}

	public void setReponseCandidats(Set<ReponseCandidat> preponseCandidats) {
		this.reponseCandidats = preponseCandidats;
	}

	public Set<Reponse> getReponses() {
		return this.reponses;
	}

	public void setReponses(Set<Reponse> preponses) {
		this.reponses = preponses;
	}

	// The following is extra code specified in the hbm.xml files   toString
	public String toString() {
		StringBuffer buffer = new StringBuffer();
		buffer.append(getClass().getName()).append("@").append(Integer.toHexString(hashCode())).append(" [");
		buffer.append("id").append("='").append(getId()).append("' ");
		buffer.append("typeSujet").append("='").append(getTypeSujet()).append("' ");
		buffer.append("libQuestion").append("='").append(getLibQuestion()).append("' ");
		buffer.append("datCreation").append("='").append(getDatCreation()).append("' ");
		buffer.append("intDureeReflexion").append("='").append(getIntDureeReflexion()).append("' ");
		buffer.append("bolUniqueReponse").append("='").append(getBolUniqueReponse()).append("' ");
		buffer.append("urlImage").append("='").append(getUrlImage()).append("' ");
		buffer.append("isValid").append("='").append(getIsValid()).append("' ");
		buffer.append("quizzQuestions").append("='").append(getQuizzQuestions()).append("' ");
		buffer.append("reponseCandidats").append("='").append(getReponseCandidats()).append("' ");
		buffer.append("reponses").append("='").append(getReponses()).append("' ");
		buffer.append("]");
		return buffer.toString();
	}

}
