package fr.gfi.quiz.entite.hibernate;

// Generated 26 mars 2014 17:52:51 by Hibernate Tools 3.4.0.CR1

/**
 * QuizzSujet generated by hbm2java
 */
public class QuizzSujet implements java.io.Serializable {

	private Integer id;
	private TypeSujet typeSujet;
	private Quizz quizz;

	public QuizzSujet() {
	}

	public QuizzSujet(TypeSujet typeSujet) {
		this.typeSujet = typeSujet;
	}

	public QuizzSujet(TypeSujet typeSujet, Quizz quizz) {
		this.typeSujet = typeSujet;
		this.quizz = quizz;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public TypeSujet getTypeSujet() {
		return this.typeSujet;
	}

	public void setTypeSujet(TypeSujet typeSujet) {
		this.typeSujet = typeSujet;
	}

	public Quizz getQuizz() {
		return this.quizz;
	}

	public void setQuizz(Quizz quizz) {
		this.quizz = quizz;
	}

}
