package fr.gfi.quiz.entite.hibernate;

// Generated 2 avr. 2014 11:27:10 by Hibernate Tools 3.4.0.CR1

/**
 *
 * QuizzQuestion generated by hbm2java
 */
public class QuizzQuestion implements java.io.Serializable {

	private Integer id;
	private Question question;
	private Quizz quizz;

	public QuizzQuestion() {
	}

	public QuizzQuestion(Question question, Quizz quizz) {
		this.question = question;
		this.quizz = quizz;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer pid) {
		this.id = pid;
	}

	public Question getQuestion() {
		return this.question;
	}

	public void setQuestion(Question pquestion) {
		this.question = pquestion;
	}

	public Quizz getQuizz() {
		return this.quizz;
	}

	public void setQuizz(Quizz pquizz) {
		this.quizz = pquizz;
	}

	// The following is extra code specified in the hbm.xml files   toString
	public String toString() {
		StringBuffer buffer = new StringBuffer();
		buffer.append(getClass().getName()).append("@").append(Integer.toHexString(hashCode())).append(" [");
		buffer.append("id").append("='").append(getId()).append("' ");
		buffer.append("question").append("='").append(getQuestion()).append("' ");
		buffer.append("quizz").append("='").append(getQuizz()).append("' ");
		buffer.append("]");
		return buffer.toString();
	}

}
