package fr.gfi.quiz.entite.hibernate;

// Generated 2 avr. 2014 11:27:10 by Hibernate Tools 3.4.0.CR1

/**
 *
 * QuizzSujet generated by hbm2java
 */
public class QuizzSujet implements java.io.Serializable {

	private Integer id;
	private TypeSujet typeSujet;
	private Quizz quizz;
	/**
	 * nombre de questions posees
	 */
	private Integer nbQuestion;
	/**
	 * nombre de bonnes r
	 */
	private Integer nbQuestionOk;
	/**
	 * nombre de questions a moitie bien repondues
	 */
	private Integer nbQuestionDemiOk;

	public QuizzSujet() {
	}

	public QuizzSujet(TypeSujet typeSujet) {
		this.typeSujet = typeSujet;
	}

	public QuizzSujet(TypeSujet typeSujet, Quizz quizz, Integer nbQuestion, Integer nbQuestionOk,
			Integer nbQuestionDemiOk) {
		this.typeSujet = typeSujet;
		this.quizz = quizz;
		this.nbQuestion = nbQuestion;
		this.nbQuestionOk = nbQuestionOk;
		this.nbQuestionDemiOk = nbQuestionDemiOk;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer pid) {
		this.id = pid;
	}

	public TypeSujet getTypeSujet() {
		return this.typeSujet;
	}

	public void setTypeSujet(TypeSujet ptypeSujet) {
		this.typeSujet = ptypeSujet;
	}

	public Quizz getQuizz() {
		return this.quizz;
	}

	public void setQuizz(Quizz pquizz) {
		this.quizz = pquizz;
	}

	/**
	 * nombre de questions posees
	 */
	public Integer getNbQuestion() {
		return this.nbQuestion;
	}

	/**
	 * nombre de questions posees
	 */
	public void setNbQuestion(Integer pnbQuestion) {
		this.nbQuestion = pnbQuestion;
	}

	/**
	 * nombre de bonnes r
	 */
	public Integer getNbQuestionOk() {
		return this.nbQuestionOk;
	}

	/**
	 * nombre de bonnes r
	 */
	public void setNbQuestionOk(Integer pnbQuestionOk) {
		this.nbQuestionOk = pnbQuestionOk;
	}

	/**
	 * nombre de questions a moitie bien repondues
	 */
	public Integer getNbQuestionDemiOk() {
		return this.nbQuestionDemiOk;
	}

	/**
	 * nombre de questions a moitie bien repondues
	 */
	public void setNbQuestionDemiOk(Integer pnbQuestionDemiOk) {
		this.nbQuestionDemiOk = pnbQuestionDemiOk;
	}

}
