package fr.gfi.quiz.entite.hibernate;

// Generated 2 avr. 2014 11:27:10 by Hibernate Tools 3.4.0.CR1

/**
 *
 * ReponseCandidat generated by hbm2java
 */
public class ReponseCandidat implements java.io.Serializable {

	private Integer id;
	private Question question;
	/**
	 * r
	 */
	private Reponse reponse;
	private Quizz quizz;

	public ReponseCandidat() {
	}

	public ReponseCandidat(Question question) {
		this.question = question;
	}

	public ReponseCandidat(Question question, Reponse reponse, Quizz quizz) {
		this.question = question;
		this.reponse = reponse;
		this.quizz = quizz;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer pid) {
		this.id = pid;
	}

	public Question getQuestion() {
		return this.question;
	}

	public void setQuestion(Question pquestion) {
		this.question = pquestion;
	}

	/**
	 * r
	 */
	public Reponse getReponse() {
		return this.reponse;
	}

	/**
	 * r
	 */
	public void setReponse(Reponse preponse) {
		this.reponse = preponse;
	}

	public Quizz getQuizz() {
		return this.quizz;
	}

	public void setQuizz(Quizz pquizz) {
		this.quizz = pquizz;
	}

	// The following is extra code specified in the hbm.xml files   toString
	public String toString() {
		StringBuffer buffer = new StringBuffer();
		buffer.append(getClass().getName()).append("@").append(Integer.toHexString(hashCode())).append(" [");
		buffer.append("id").append("='").append(getId()).append("' ");
		buffer.append("question").append("='").append(getQuestion()).append("' ");
		buffer.append("reponse").append("='").append(getReponse()).append("' ");
		buffer.append("quizz").append("='").append(getQuizz()).append("' ");
		buffer.append("]");
		return buffer.toString();
	}

}
