package fr.gfi.quiz.entite.hibernate;

// Generated 2 avr. 2014 11:27:10 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 *
 * Role generated by hbm2java
 */
public class Role implements java.io.Serializable {

	private int id;
	private String libRole;
	private Set<UserRoles> userRoleses = new HashSet<UserRoles>(0);

	public Role() {
	}

	public Role(int id, String libRole) {
		this.id = id;
		this.libRole = libRole;
	}

	public Role(int id, String libRole, Set<UserRoles> userRoleses) {
		this.id = id;
		this.libRole = libRole;
		this.userRoleses = userRoleses;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int pid) {
		this.id = pid;
	}

	public String getLibRole() {
		return this.libRole;
	}

	public void setLibRole(String plibRole) {
		this.libRole = plibRole;
	}

	public Set<UserRoles> getUserRoleses() {
		return this.userRoleses;
	}

	public void setUserRoleses(Set<UserRoles> puserRoleses) {
		this.userRoleses = puserRoleses;
	}

	// The following is extra code specified in the hbm.xml files   toString
	public String toString() {
		StringBuffer buffer = new StringBuffer();
		buffer.append(getClass().getName()).append("@").append(Integer.toHexString(hashCode())).append(" [");
		buffer.append("id").append("='").append(getId()).append("' ");
		buffer.append("libRole").append("='").append(getLibRole()).append("' ");
		buffer.append("userRoleses").append("='").append(getUserRoleses()).append("' ");
		buffer.append("]");
		return buffer.toString();
	}

}
