package fr.gfi.quiz.entite.hibernate;

// Generated 14 avr. 2014 16:36:23 by Hibernate Tools 4.0.0

/**
 * SujetId generated by hbm2java
 */
public class SujetId implements java.io.Serializable {

	private int id;
	private int refDifficulte;

	public SujetId() {
	}

	public SujetId(int id, int refDifficulte) {
		this.id = id;
		this.refDifficulte = refDifficulte;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public int getRefDifficulte() {
		return this.refDifficulte;
	}

	public void setRefDifficulte(int refDifficulte) {
		this.refDifficulte = refDifficulte;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SujetId))
			return false;
		SujetId castOther = (SujetId) other;

		return (this.getId() == castOther.getId())
				&& (this.getRefDifficulte() == castOther.getRefDifficulte());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getId();
		result = 37 * result + this.getRefDifficulte();
		return result;
	}

}
