package fr.gfi.quiz.entite.hibernate;

// Generated 14 avr. 2014 16:36:23 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * Sujet generated by hbm2java
 */
public class Sujet implements java.io.Serializable {

	private SujetId id;
	private Difficulte difficulte;
	private Theme theme;
	private String libelle;
	private Set<Question> questions = new HashSet<Question>(0);
	private Set<QuizzSujet> quizzSujets = new HashSet<QuizzSujet>(0);

	public Sujet() {
	}

	public Sujet(SujetId id, Difficulte difficulte, Theme theme, String libelle) {
		this.id = id;
		this.difficulte = difficulte;
		this.theme = theme;
		this.libelle = libelle;
	}

	public Sujet(SujetId id, Difficulte difficulte, Theme theme,
			String libelle, Set<Question> questions, Set<QuizzSujet> quizzSujets) {
		this.id = id;
		this.difficulte = difficulte;
		this.theme = theme;
		this.libelle = libelle;
		this.questions = questions;
		this.quizzSujets = quizzSujets;
	}

	public SujetId getId() {
		return this.id;
	}

	public void setId(SujetId id) {
		this.id = id;
	}

	public Difficulte getDifficulte() {
		return this.difficulte;
	}

	public void setDifficulte(Difficulte difficulte) {
		this.difficulte = difficulte;
	}

	public Theme getTheme() {
		return this.theme;
	}

	public void setTheme(Theme theme) {
		this.theme = theme;
	}

	public String getLibelle() {
		return this.libelle;
	}

	public void setLibelle(String libelle) {
		this.libelle = libelle;
	}

	public Set<Question> getQuestions() {
		return this.questions;
	}

	public void setQuestions(Set<Question> questions) {
		this.questions = questions;
	}

	public Set<QuizzSujet> getQuizzSujets() {
		return this.quizzSujets;
	}

	public void setQuizzSujets(Set<QuizzSujet> quizzSujets) {
		this.quizzSujets = quizzSujets;
	}

}
