package fr.gfi.quiz.entite.hibernate;

// Generated 26 mars 2014 17:52:51 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * TypeSujet generated by hbm2java
 */
public class TypeSujet implements java.io.Serializable {

	private TypeSujetId id;
	private Difficulte difficulte;
	private Langage langage;
	private String libelle;
	private Set<Question> questions = new HashSet<Question>(0);
	private Set<QuizzSujet> quizzSujets = new HashSet<QuizzSujet>(0);

	public TypeSujet() {
	}

	public TypeSujet(TypeSujetId id, Difficulte difficulte, Langage langage,
			String libelle) {
		this.id = id;
		this.difficulte = difficulte;
		this.langage = langage;
		this.libelle = libelle;
	}

	public TypeSujet(TypeSujetId id, Difficulte difficulte, Langage langage,
			String libelle, Set<Question> questions, Set<QuizzSujet> quizzSujets) {
		this.id = id;
		this.difficulte = difficulte;
		this.langage = langage;
		this.libelle = libelle;
		this.questions = questions;
		this.quizzSujets = quizzSujets;
	}

	public TypeSujetId getId() {
		return this.id;
	}

	public void setId(TypeSujetId id) {
		this.id = id;
	}

	public Difficulte getDifficulte() {
		return this.difficulte;
	}

	public void setDifficulte(Difficulte difficulte) {
		this.difficulte = difficulte;
	}

	public Langage getLangage() {
		return this.langage;
	}

	public void setLangage(Langage langage) {
		this.langage = langage;
	}

	public String getLibelle() {
		return this.libelle;
	}

	public void setLibelle(String libelle) {
		this.libelle = libelle;
	}

	public Set<Question> getQuestions() {
		return this.questions;
	}

	public void setQuestions(Set<Question> questions) {
		this.questions = questions;
	}

	public Set<QuizzSujet> getQuizzSujets() {
		return this.quizzSujets;
	}

	public void setQuizzSujets(Set<QuizzSujet> quizzSujets) {
		this.quizzSujets = quizzSujets;
	}

}
