package fr.gfi.quiz.entite.hibernate;

// Generated Mar 19, 2014 12:00:06 AM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User implements java.io.Serializable {

	private Integer id;
	private String nom;
	private String prenom;
	private String login;
	private String password;
	private Set<Quizz> quizzs = new HashSet<Quizz>(0);
	private Set<UserRoles> userRoleses = new HashSet<UserRoles>(0);

	public User() {
	}

	public User(String nom, String prenom, String login, String password,
			Set<Quizz> quizzs, Set<UserRoles> userRoleses) {
		this.nom = nom;
		this.prenom = prenom;
		this.login = login;
		this.password = password;
		this.quizzs = quizzs;
		this.userRoleses = userRoleses;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	public String getPrenom() {
		return this.prenom;
	}

	public void setPrenom(String prenom) {
		this.prenom = prenom;
	}

	public String getLogin() {
		return this.login;
	}

	public void setLogin(String login) {
		this.login = login;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public Set<Quizz> getQuizzs() {
		return this.quizzs;
	}

	public void setQuizzs(Set<Quizz> quizzs) {
		this.quizzs = quizzs;
	}

	public Set<UserRoles> getUserRoleses() {
		return this.userRoleses;
	}

	public void setUserRoleses(Set<UserRoles> userRoleses) {
		this.userRoleses = userRoleses;
	}

}
