package fr.gfi.cmg.QuizzCmg.metier.entite.hibernate;

// Generated 2 août 2013 10:03:09 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Langage generated by hbm2java
 */
public class Langage implements java.io.Serializable {

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + id;
		result = prime * result + ((libelle == null) ? 0 : libelle.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Langage other = (Langage) obj;
		if (id != other.id)
			return false;
		if (libelle == null) {
			if (other.libelle != null)
				return false;
		} else if (!libelle.equals(other.libelle))
			return false;
		return true;
	}

	private int id;
	private String libelle;
	private Set<TypeSujet> typeSujets = new HashSet<TypeSujet>(0);

	public Langage() {
	}

	public Langage(int id, String libelle) {
		this.id = id;
		this.libelle = libelle;
	}

	public Langage(int id, String libelle, Set<TypeSujet> typeSujets) {
		this.id = id;
		this.libelle = libelle;
		this.typeSujets = typeSujets;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getLibelle() {
		return this.libelle;
	}

	public void setLibelle(String libelle) {
		this.libelle = libelle;
	}

	public Set<TypeSujet> getTypeSujets() {
		return this.typeSujets;
	}

	public void setTypeSujets(Set<TypeSujet> typeSujets) {
		this.typeSujets = typeSujets;
	}

}
