package fr.gfi.cmg.QuizzCmg.metier.entite.hibernate;

// Generated 17 sept. 2013 17:50:17 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * NiveauQuestion generated by hbm2java
 */
public class NiveauQuestion implements java.io.Serializable {

	private Integer id;
	private String libNiveau;
	private Set<Question> questions = new HashSet<Question>(0);
	private Set<QuizzSujet> quizzSujets = new HashSet<QuizzSujet>(0);

	public NiveauQuestion() {
	}

	public NiveauQuestion(String libNiveau, Set<Question> questions, Set<QuizzSujet> quizzSujets) {
		this.libNiveau = libNiveau;
		this.questions = questions;
		this.quizzSujets = quizzSujets;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getLibNiveau() {
		return this.libNiveau;
	}

	public void setLibNiveau(String libNiveau) {
		this.libNiveau = libNiveau;
	}

	public Set<Question> getQuestions() {
		return this.questions;
	}

	public void setQuestions(Set<Question> questions) {
		this.questions = questions;
	}

	public Set<QuizzSujet> getQuizzSujets() {
		return this.quizzSujets;
	}

	public void setQuizzSujets(Set<QuizzSujet> quizzSujets) {
		this.quizzSujets = quizzSujets;
	}

}
