package fr.gfi.cmg.QuizzCmg.metier.entite.hibernate;

// Generated 2 août 2013 10:03:09 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * TypeSujet generated by hbm2java
 */
public class TypeSujet implements java.io.Serializable {

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		result = prime * result + ((langage == null) ? 0 : langage.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		TypeSujet other = (TypeSujet) obj;
		if (id == null) {
			if (other.id != null)
				return false;
		} else if (!id.equals(other.id))
			return false;
		if (langage == null) {
			if (other.langage != null)
				return false;
		} else if (!langage.equals(other.langage))
			return false;
		return true;
	}

	private Integer id;
	private Langage langage;
	private String libelle;
	private Set<Question> questions = new HashSet<Question>(0);
	private Set<QuizzSujet> quizzSujets = new HashSet<QuizzSujet>(0);

	public TypeSujet() {
	}

	public TypeSujet(Integer id, String libelle) {
		
		this.id = id;		
		this.libelle = libelle;
	}

	public TypeSujet(Langage langage, String libelle) {
		this.langage = langage;
		this.libelle = libelle;
	}

	public TypeSujet(Langage langage, String libelle, Set<Question> questions,
			Set<QuizzSujet> quizzSujets) {
		this.langage = langage;
		this.libelle = libelle;
		this.questions = questions;
		this.quizzSujets = quizzSujets;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Langage getLangage() {
		return this.langage;
	}

	public void setLangage(Langage langage) {
		this.langage = langage;
	}

	public String getLibelle() {
		return this.libelle;
	}

	public void setLibelle(String libelle) {
		this.libelle = libelle;
	}

	public Set<Question> getQuestions() {
		return this.questions;
	}

	public void setQuestions(Set<Question> questions) {
		this.questions = questions;
	}

	public Set<QuizzSujet> getQuizzSujets() {
		return this.quizzSujets;
	}

	public void setQuizzSujets(Set<QuizzSujet> quizzSujets) {
		this.quizzSujets = quizzSujets;
	}

}
